### ISSUE TITLE
Temperature Bug?

### ISSUE THREAD

**Issue by colinluthier** [bolderflight/ams5915-arduino#1]
Running the sample code on a AMS5915_0050_D give an ambient temperature of -41.73C in my office (It is actually about 20C). Looking at the data sheet it contradicts itself. https://media.ncd.io/sites/2/20170721134814/ams5915-3.pdf

"The current sensor temperature in °C is calculated from the digital temperature value using the following
formula:
((DigoutT(T)* 200)/2048)+50
But in the datasheet example:
((743 * 200) counts * C)/2048 counts)-50=22.6 C"

From the C code:
 _data.Temp_C = (float)((_temperatureCounts*200))/2048.0f-50.0f;

I am not sure if I have a hardware error or a code error.

Note: I downloaded the code with the Arduino Library manager.

**Comment by flybrianfly** [comment]
All 3 of these seem equivalent to me:
>((DigoutT(T)* 200)/2048)+50
>((743 * 200) counts * C)/2048 counts)-50=22.6 C"
>_data.Temp_C = (float)((_temperatureCounts*200))/2048.0f-50.0f;

I just checked the temperature and pressure on an AMS-5915 1200B while updating the library and I'm getting normal temperature readings for my office; about 23C a little above ambient as expected. I would suspect a hardware issue.

**Comment by colinluthier** [comment]
So the -50 constant is correct for your hardware? Not the +50?

Thank you!

**Comment by flybrianfly** [comment]
Oh, thanks for pointing that out! I didn't notice the difference in sign. I have a newer version of the data sheet here:
https://github.com/bolderflight/ams5915-arduino/blob/main/docs/ams5915.pdf

You'll notice on page 9 that it uses a -50 instead of +50, matching the example and the code. Must have been a typo in the older data sheet that later got fixed. I can confirm that the -50 constant is correct.

**Comment by colinluthier** [comment]
Thank you!
